apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-producer
spec:
  selector:
    matchLabels:
      app: model-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: model-producer
    spec:
      containers:
        - name: model-producer
          image: model-producer
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_HOST
              value: "kafka:9092"
