apiVersion: v1
kind: Service
metadata:
  name: model-producer
  labels:
    app: model-producer
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32080
  selector:
    app: model-producer
