# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.prediction_input_data import PredictionInputData  # noqa: F401,E501
from swagger_server import util


class PredctionGetBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_data: PredictionInputData=None):  # noqa: E501
        """PredctionGetBody - a model defined in Swagger

        :param input_data: The input_data of this PredctionGetBody.  # noqa: E501
        :type input_data: PredictionInputData
        """
        self.swagger_types = {
            'input_data': PredictionInputData
        }

        self.attribute_map = {
            'input_data': 'input_data'
        }
        self._input_data = input_data

    @classmethod
    def from_dict(cls, dikt) -> 'PredctionGetBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predctionGetBody of this PredctionGetBody.  # noqa: E501
        :rtype: PredctionGetBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_data(self) -> PredictionInputData:
        """Gets the input_data of this PredctionGetBody.


        :return: The input_data of this PredctionGetBody.
        :rtype: PredictionInputData
        """
        return self._input_data

    @input_data.setter
    def input_data(self, input_data: PredictionInputData):
        """Sets the input_data of this PredctionGetBody.


        :param input_data: The input_data of this PredctionGetBody.
        :type input_data: PredictionInputData
        """
        if input_data is None:
            raise ValueError("Invalid value for `input_data`, must not be `None`")  # noqa: E501

        self._input_data = input_data
